data: 
    data_path: data/raw/training_dataset/
    test_data_path: data/raw/lis_dataset/
    train_size: 0.8
    test_size: 0.05
    val_size: 0.15
    batch_size: 8
    resize_dims: 64
    enable_transforms: True
    num_workers: 0
    random_state: 2023
model:
    name: unet # unet #deeplab
    unet_block : "cnn" # can be also "resnet"
    in_channels: 1
    out_channels: 3
    save_model: True
    save_path: models/
training:
    optimizer: adam
    lr : 0.001
    epochs: 10
    seed : 69